version = 1

test_patterns = [
    "app/src/androidTest/**/*.*",
    "app/src/test/**.*.*"
]

[[analyzers]]
name = "java"
enabled = true

  [analyzers.meta]
  runtime_version = "8"

[[transformers]]
name = "prettier"
enabled = true
